### ISSUE TITLE
new domains to add

### ISSUE THREAD

**Issue by iteqla** [Amdr0meda/Blocklist_Pi_Hole#6]
Hi,
you might want to add following domains to the porn blocker

arthyredir.com
finddateslocally.com
endler.it
guppies.com
amazing-flirt.life

Sadly, endler.it and guppies.com used to be a website about fish-keeping but as they did not renew their subscription, it was taken over by dodgy ones who now redirect to porn-like sites masked as dating sites :-(

**Comment by Amdr0meda** [comment]
Hello, the domains are pending for a new version in the next few days. Thanks for the input
